const languageData = {
  languages: [
    { lang: 'English', code: 'en', ui: 'EN', flag: '/flags/gb.svg' },
    { lang: 'Afrikaans', code: 'af', ui: 'AF', flag: '/flags/za.svg' },
    { lang: 'Albanian', code: 'sq', ui: 'SQ', flag: '/flags/al.svg' },
    { lang: 'Amharic', code: 'am', ui: 'AM', flag: '/flags/et.svg' },
    { lang: 'Arabic', code: 'ar', ui: 'AR', flag: '/flags/sa.svg' },
    { lang: 'Armenian', code: 'hy', ui: 'HY', flag: '/flags/am.svg' },
    { lang: 'Azerbaijani', code: 'az', ui: 'AZ', flag: '/flags/az.svg' },
    { lang: 'Basque', code: 'eu', ui: 'EU', flag: '/flags/es.svg' },
    { lang: 'Belarusian', code: 'be', ui: 'BE', flag: '/flags/by.svg' },
    { lang: 'Bengali', code: 'bn', ui: 'BN', flag: '/flags/bd.svg' },
    { lang: 'Bosnian', code: 'bs', ui: 'BS', flag: '/flags/ba.svg' },
    { lang: 'Bulgarian', code: 'bg', ui: 'BG', flag: '/flags/bg.svg' },
    { lang: 'Catalan', code: 'ca', ui: 'CA', flag: '/flags/es.svg' },
    { lang: 'Chinese', code: 'zh', ui: 'ZH', flag: '/flags/cn.svg' },
    { lang: 'Corsican', code: 'co', ui: 'CO', flag: '/flags/fr.svg' },
    { lang: 'Croatian', code: 'hr', ui: 'HR', flag: '/flags/hr.svg' },
    { lang: 'Czech', code: 'cs', ui: 'CS', flag: '/flags/cz.svg' },
    { lang: 'Danish', code: 'da', ui: 'DA', flag: '/flags/dk.svg' },
    { lang: 'Dutch', code: 'nl', ui: 'NL', flag: '/flags/nl.svg' },
    { lang: 'Esperanto', code: 'eo', ui: 'EO', flag: '/flags/eu.svg' }, // якщо нема — заміниш/видалиш
    { lang: 'Estonian', code: 'et', ui: 'ET', flag: '/flags/ee.svg' },
    { lang: 'Finnish', code: 'fi', ui: 'FI', flag: '/flags/fi.svg' },
    { lang: 'French', code: 'fr', ui: 'FR', flag: '/flags/fr.svg' },
    { lang: 'Frisian', code: 'fy', ui: 'FY', flag: '/flags/nl.svg' },
    { lang: 'Galician', code: 'gl', ui: 'GL', flag: '/flags/es.svg' },
    { lang: 'Georgian', code: 'ka', ui: 'KA', flag: '/flags/ge.svg' },
    { lang: 'German', code: 'de', ui: 'DE', flag: '/flags/de.svg' },
    { lang: 'Greek', code: 'el', ui: 'EL', flag: '/flags/gr.svg' },
    { lang: 'Gujarati', code: 'gu', ui: 'GU', flag: '/flags/in.svg' },
    { lang: 'Haitian Creole', code: 'ht', ui: 'HT', flag: '/flags/ht.svg' },
    { lang: 'Hausa', code: 'ha', ui: 'HA', flag: '/flags/ng.svg' },
    { lang: 'Hebrew', code: 'he', ui: 'HE', flag: '/flags/il.svg' },
    { lang: 'Hindi', code: 'hi', ui: 'HI', flag: '/flags/in.svg' },
    { lang: 'Hungarian', code: 'hu', ui: 'HU', flag: '/flags/hu.svg' },
    { lang: 'Icelandic', code: 'is', ui: 'IS', flag: '/flags/is.svg' },
    { lang: 'Igbo', code: 'ig', ui: 'IG', flag: '/flags/ng.svg' },
    { lang: 'Indonesian', code: 'id', ui: 'ID', flag: '/flags/id.svg' },
    { lang: 'Irish', code: 'ga', ui: 'GA', flag: '/flags/ie.svg' },
    { lang: 'Italian', code: 'it', ui: 'IT', flag: '/flags/it.svg' },
    { lang: 'Japanese', code: 'ja', ui: 'JA', flag: '/flags/jp.svg' },
    { lang: 'Javanese', code: 'jv', ui: 'JV', flag: '/flags/id.svg' },
    { lang: 'Kannada', code: 'kn', ui: 'KN', flag: '/flags/in.svg' },
    { lang: 'Kazakh', code: 'kk', ui: 'KK', flag: '/flags/kz.svg' },
    { lang: 'Khmer', code: 'km', ui: 'KM', flag: '/flags/kh.svg' },
    { lang: 'Kinyarwanda', code: 'rw', ui: 'RW', flag: '/flags/rw.svg' },
    { lang: 'Korean', code: 'ko', ui: 'KO', flag: '/flags/kr.svg' },
    { lang: 'Kurdish', code: 'ku', ui: 'KU', flag: '/flags/iq.svg' },
    { lang: 'Kyrgyz', code: 'ky', ui: 'KY', flag: '/flags/kg.svg' },
    { lang: 'Lao', code: 'lo', ui: 'LO', flag: '/flags/la.svg' },
    { lang: 'Latin', code: 'la', ui: 'LA', flag: '/flags/va.svg' },
    { lang: 'Latvian', code: 'lv', ui: 'LV', flag: '/flags/lv.svg' },
    { lang: 'Lithuanian', code: 'lt', ui: 'LT', flag: '/flags/lt.svg' },
    { lang: 'Luxembourgish', code: 'lb', ui: 'LB', flag: '/flags/lu.svg' },
    { lang: 'Macedonian', code: 'mk', ui: 'MK', flag: '/flags/mk.svg' },
    { lang: 'Malagasy', code: 'mg', ui: 'MG', flag: '/flags/mg.svg' },
    { lang: 'Malay', code: 'ms', ui: 'MS', flag: '/flags/my.svg' },
    { lang: 'Malayalam', code: 'ml', ui: 'ML', flag: '/flags/in.svg' },
    { lang: 'Maltese', code: 'mt', ui: 'MT', flag: '/flags/mt.svg' },
    { lang: 'Maori', code: 'mi', ui: 'MI', flag: '/flags/nz.svg' },
    { lang: 'Marathi', code: 'mr', ui: 'MR', flag: '/flags/in.svg' },
    { lang: 'Mongolian', code: 'mn', ui: 'MN', flag: '/flags/mn.svg' },
    { lang: 'Myanmar', code: 'my', ui: 'MY', flag: '/flags/mm.svg' },
    { lang: 'Nepali', code: 'ne', ui: 'NE', flag: '/flags/np.svg' },
    { lang: 'Norwegian', code: 'no', ui: 'NO', flag: '/flags/no.svg' },
    { lang: 'Nyanja (Chichewa)', code: 'ny', ui: 'NY', flag: '/flags/mw.svg' },
    { lang: 'Odia(Oriya)', code: 'or', ui: 'OR', flag: '/flags/in.svg' },
    { lang: 'Pashto', code: 'ps', ui: 'PS', flag: '/flags/af.svg' },
    { lang: 'Persian', code: 'fa', ui: 'FA', flag: '/flags/ir.svg' },
    { lang: 'Polish', code: 'pl', ui: 'PL', flag: '/flags/pl.svg' },
    { lang: 'Portuguese(Portugal, Brazil)', code: 'pt', ui: 'PT', flag: '/flags/pt.svg' },
    { lang: 'Punjabi', code: 'pa', ui: 'PA', flag: '/flags/in.svg' },
    { lang: 'Romanian', code: 'ro', ui: 'RO', flag: '/flags/ro.svg' },
    { lang: 'Russian', code: 'ru', ui: 'RU', flag: '/flags/ru.svg' },
    { lang: 'Samoan', code: 'sm', ui: 'SM', flag: '/flags/ws.svg' },
    { lang: 'Scots Gaelic', code: 'gd', ui: 'GD', flag: '/flags/gb.svg' },
    { lang: 'Serbian', code: 'sr', ui: 'SR', flag: '/flags/rs.svg' },
    { lang: 'Sesotho', code: 'st', ui: 'ST', flag: '/flags/ls.svg' },
    { lang: 'Shona', code: 'sn', ui: 'SN', flag: '/flags/zw.svg' },
    { lang: 'Sindhi', code: 'sd', ui: 'SD', flag: '/flags/pk.svg' },
    { lang: 'Sinhala(Sinhalese)', code: 'si', ui: 'SI', flag: '/flags/lk.svg' },
    { lang: 'Slovak', code: 'sk', ui: 'SK', flag: '/flags/sk.svg' },
    { lang: 'Slovenian', code: 'sl', ui: 'SL', flag: '/flags/si.svg' },
    { lang: 'Somali', code: 'so', ui: 'SO', flag: '/flags/so.svg' },
    { lang: 'Spanish', code: 'es', ui: 'ES', flag: '/flags/es.svg' },
    { lang: 'Sundanese', code: 'su', ui: 'SU', flag: '/flags/id.svg' },
    { lang: 'Swahili', code: 'sw', ui: 'SW', flag: '/flags/tz.svg' },
    { lang: 'Swedish', code: 'sv', ui: 'SV', flag: '/flags/se.svg' },
    { lang: 'Tagalog(Filipino)', code: 'tl', ui: 'TL', flag: '/flags/ph.svg' },
    { lang: 'Tajik', code: 'tg', ui: 'TG', flag: '/flags/tj.svg' },
    { lang: 'Tamil', code: 'ta', ui: 'TA', flag: '/flags/in.svg' },
    { lang: 'Tatar', code: 'tt', ui: 'TT', flag: '/flags/ru.svg' },
    { lang: 'Telugu', code: 'te', ui: 'TE', flag: '/flags/in.svg' },
    { lang: 'Thai', code: 'th', ui: 'TH', flag: '/flags/th.svg' },
    { lang: 'Turkish', code: 'tr', ui: 'TR', flag: '/flags/tr.svg' },
    { lang: 'Turkmen', code: 'tk', ui: 'TK', flag: '/flags/tm.svg' },
    { lang: 'Ukrainian', code: 'uk', ui: 'UA', flag: '/flags/ua.svg' },
    { lang: 'Urdu', code: 'ur', ui: 'UR', flag: '/flags/pk.svg' },
    { lang: 'Uyghur', code: 'ug', ui: 'UG', flag: '/flags/cn.svg' },
    { lang: 'Uzbek', code: 'uz', ui: 'UZ', flag: '/flags/uz.svg' },
    { lang: 'Vietnamese', code: 'vi', ui: 'VI', flag: '/flags/vn.svg' },
    { lang: 'Welsh', code: 'cy', ui: 'CY', flag: '/flags/gb.svg' },
    { lang: 'Xhosa', code: 'xh', ui: 'XH', flag: '/flags/za.svg' },
    { lang: 'Yiddish', code: 'yi', ui: 'YI', flag: '/flags/il.svg' },
    { lang: 'Yoruba', code: 'yo', ui: 'YO', flag: '/flags/ng.svg' },
    { lang: 'Zulu', code: 'zu', ui: 'ZU', flag: '/flags/za.svg' },
  ],
}

export default languageData
